### ISSUE TITLE
Simple approach: Start and end positions of viewpoint beyond restriction sites of TSS containing fragment

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#77]
If I use the simple approach with the following arguments:

![image](https://user-images.githubusercontent.com/10495485/32113341-49b4e0aa-bb40-11e7-87da-36a59886fd7a.png)

I find at least one example for which the start and end positions of the viewpoint go beyond the restriction sites of the TSS containing fragment, which is smaller than the required 130 bp.

![image](https://user-images.githubusercontent.com/10495485/32113441-9d983b0e-bb40-11e7-9cba-2607aad8dce9.png)

Also the start and end positions of the viewpoint does not coincide with a restriction site.

![image](https://user-images.githubusercontent.com/10495485/32113588-085bd73e-bb41-11e7-8d51-134a80fc2c93.png)

There is no selected fragment for this viewpoint, which is correct, because the TSS containing fragment is too small. But in this case there should not be any viewpoint at all.

**Comment by pnrobinson** [comment]
I am not sure I understand. VPV shows viewpoints with no fragments so that a user can decide to choose a fragment if he/she chooses. 
![image](https://user-images.githubusercontent.com/4943420/32389809-4b1f90ae-c0a2-11e7-83e1-a674aec48154.png)

This is a typical image (note that the overall size of the display was changed recently.
Does this work now?
If not, what should be changed?

**Comment by hansenp** [comment]
The problem was that viewpoints without selected fragments were exported to BED and that the start and end coordinates of those viewpoints were wrong. This has been solved in issue #86 by skipping viewpoints with 0 selected fragments when exporting to BED. Therefore, I will close this issue.
