### ISSUE TITLE
Maximum repeat content (%) = 7000.00

### ISSUE THREAD

**Issue by hannahblau** [TheJacksonLaboratory/VPV#83]
This is the default value. See attached screenshot.
![maxrepeat](https://user-images.githubusercontent.com/8484992/32392188-f30ca998-c0aa-11e7-9743-bd4defce0506.png)

**Comment by pnrobinson** [comment]
This error was related to conversion from percent (GUI) to proportion (Model) and back. I have modified several things so that the GUI now shows prompts with default values when the user starts a new project, but nothing is initialized unless the user actually enters something. 
Possibly old projects might have percentages vs proportions and this will need to be corrected in the GUI, but then all should be OK.
