### ISSUE TITLE
Simple approach: Set marginSize=probeLength

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#91]
For the simple approach only two probes should be selected for each end of TSS containing fragments. If the simple approach is considered as a special case of the extended approach, it might be reasonable to set _marginSize=probeLength_ fot the simple approach.

Currently, the _marginSize_ has to be set manually to 120 if the simple approach is used.

**Comment by pnrobinson** [comment]
@hansenp  Well, our method does not need to be exactly like capsequm, and perhaps it makes more sense to let the use choose margin size to be whatever? On the other hand, with the way we have implemented simple approach, Margin size will not have any effect because we only choose one probe per promoter anyway. I would say that we can probably leave it as is but I would like to write a longer explanation on the dialog (I do not think you checked in your text by the way).

**Comment by hansenp** [comment]
Ok. I needed it to compare our target regions to that of CapSequm. To do this, I had to set the marginSize to one probeLength.

I will check in the text for the dialog tomorrow.

**Comment by hansenp** [comment]
...done.
