### ISSUE TITLE
Flag for viewpoints with active center fragment

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#99]
Maybe it would be interesting for many users, if there was a flag for viewpoints that indicates whether the TSS containing fragment is active or not.

**Comment by pnrobinson** [comment]
I have now added an asterix (*) to all target names where the center fragment is selected. 
We could also make a separate column, which would allow users to sort on center-column selectedness. Please have a look @hansenp

**Comment by pnrobinson** [comment]
@hansenp On second thought I added a separate column so that the user can sort.
IMPORTANT -- note that you will need to create a new viewpoint set and save it for the results to be visible after you open a previous model. We need to update the serial ID for Model but I am holding off because of the current analysis with the various saved models.

**Comment by hansenp** [comment]
> On second thought I added a separate column so that the user can sort.

Yes, this would be useful.

> IMPORTANT -- note that you will need to create a new viewpoint set and save it for the results to be visible after you open a previous model.

I'm not sure, if I understand correctly. Do you mean that the new feature is available only for viewpoint sets created after the modification?

**Comment by pnrobinson** [comment]
Since this is a new feature, if you open an old project file, it will not be accurate (it will show all NO, I think). You need to run the "create viewpoint" function and then all will be OK. Usually, when you make a change like this you need to increment the serial ID (this would cause an exception when an old file is opened). I did not do so because you are working with many project files now. I think everything is fine, this was just a heads up!
